### ISSUE TITLE
ronn fails when building from a tarball

### ISSUE THREAD

**Issue by sandrotosi** [mprovost/NFStash#20]
```
$ make
ronn --date `git log -n1 --pretty=format:%ci -- man/nfsping.8.ronn | cut -f1 -d" "` --style=toc man/nfsping.8.ronn
fatal: Not a git repository (or any of the parent directories): .git
/usr/bin/ronn:133:in `strptime': invalid date (ArgumentError)
	from /usr/bin/ronn:133:in `<main>'
Makefile:43: recipe for target 'man/nfsping.8' failed
make: *** [man/nfsping.8] Error 1
```

it is not a git repo indeed :)

maybe you can consider something along the line of

```
$ stat man/nfslock.8.ronn | awk '/Change/ { print $2 }'
2016-09-01
```

or some changelog/release file you can fetch the date from it?

i wouldnt use the current date as the reproducible build folks (https://reproducible-builds.org/) will surely have something to say about it :)

**Comment by mprovost** [comment]
I've never built it from a tarball myself (obviously). I was never that
happy with using git for dates because it requires two commits for the HTML
pages. But it works well because the date in the manpages always matches
the last date that the source ronn file changed. Otherwise git changes
mtimes when you change branches which was causing them all to be updated. I
might be able to put a hook in to reset the mtime on the source files to
the last commit date.

**Comment by sandrotosi** [comment]
yeah i dont have a  great solution, for the debian packaging i used the stat thing, just because i needed something that will return always the same date and could be achieved with standard cli tools
